document.write("<center><h1 style=background-color:black;color:white;>Professional CV</h1></center>")
document.write("<br><center><h2 style=background-color:black;color:white;>Personal Information</h2></center>")
document.write("<br><h2>Name:Muhammad Hassan Raza</h2>")
document.write("<h2>Father Name:Ahmed Raza</h2>")
document.write("<h2>Age:16</h2>") 
document.write("<h2>Email:hr7762930@gmail.com</h2>")
document.write("<h2>Contact:03111769131</h2>")
document.write("<hr> <br><center><h1  style=background-color:black;color:white;>Skills</h1></center>")
document.write("<h2>1- web devlopment</h2    >")
document.write("<hr><br><center><h1 style=background-color:black;color:white;>Qualification</h1></center>")
document.write("<h2> metric in 2024</h2>")
